### ISSUE TITLE
Fix display of new messages

### ISSUE THREAD

**Issue by sigmavirus24** [Lukasa/pyrc#12]
![pyrc](https://f.cloud.github.com/assets/240830/1830454/82a7c736-7343-11e3-9ee1-d494eb194846.png)

**Comment by sigmavirus24** [comment]
FWIW, I'm apparently still on Firefox 21.0 (if in fact it's a browser issue)

**Comment by Lukasa** [comment]
I think that this will probably be fixed by 1b70128b79e8cf3fa5b8b84e04ea4cf1fab36c6f. I'll update the running release of PyRC in a little bit and we can retest it.

**Comment by Lukasa** [comment]
Ok, PyRC is running a version of the code with this fix in it, give it a whirl.

**Comment by sigmavirus24** [comment]
![pyrc](https://f.cloud.github.com/assets/240830/1845193/432173d4-7576-11e3-9906-baf4d7b75f40.png)
